rm(list = ls())
library(here)
library(tidyverse)
source("R/LDFunctions.R")

# Generated by vcftools for the entire VCF file
LD <- read.table(file = "data/r2-chr8-thin_1000", sep="\t", header=TRUE, stringsAsFactors = F)

LD <- LD[-is.na(LD$R.2),]

LD$CHROM_A <- 8
LD$CHROM_B <- 8
LD <- LD[,-c(1,4)]
LD <- LD[,c(4,1,5,2,3)]
colnames(LD) <- c("CHROM_A", "POS_A", "CHROM_B", "POS_B", "R2")

png("Figures/genowide.png", units="in", width=15, height=10, res=750)
plotPairwiseLD(LD)
dev.off()
