rm(list = ls())
library(here)
library(tidyverse)
library(qqman)
source("R/LDFunctions.R")

# Generated by vcftools for the entire VCF file
# vcftools --vcf dean_converted.vcf --geno-r2 --ld-window 100


# Generated by vcftools for the entire VCF file
# vcftools --vcf dean_converted.vcf --geno-r2 --ld-window 100
LD <- read.table(file = "data/r2-ldwindow_100", sep="\t", header=TRUE, stringsAsFactors = F)
LD <- read.table(file = "data/dean-d10-thin-1000-ldwindow-100.ld", sep="\t", header=TRUE, stringsAsFactors = F)


# Split big matrix into list separated into chromosomes
LD.by.chroms <- splitByChrom(LD, nchrom = 9, sep = "")

# Loop over chromosomes and get the mean r2 in each window
LD.by.window <- slidingWindow(LD.by.chroms, windowSize = 100)

LD.by.window <- nonOverlappingWindow(LD.by.chroms, windowSize = 100)


#save(LD.by.window, file = "r2SlidingWindow.RData")

allchroms <- LD.by.window[[10]]
allchroms <- allchroms[-c(which(is.na(allchroms$r2))),]

png("Figures/r2nonOverlappingWindow-100SNPs.png", units="in", width=15, height=10, res=750)
manhattan(allchroms, chr = "chr", bp = "bp", p = "r2", logp = F, suggestiveline = F, genomewideline = F, ylab = expression("Linkage disequilbrium"~(r^{2})))
dev.off()



